### PR TITLE
Made service classes configurable via parameters

### PR DESCRIPTION
**Pull request by silasjoisten**
I am targetting this branch, because this is BC.

## Changelog

```markdown
### Changed
- Made service classes configurable via parameters
```

### CODE REVIEW

**Comment by greg0ire** [comment]
We do not allow this by policy. Why do you need this?

**Comment by OskarStark** [comment]
> We do not allow this by policy. Why do you need this?

@greg0ire why don't we allow this by policy, currently it is not possible to change the used `AdminExtension`

**Comment by greg0ire** [comment]
We want to know why people would want to change it, and make the class itself more flexible, by adding the necessary code to allow the same behavior.

**Comment by OskarStark** [comment]
@silasjoisten can you please explain what is currently NOT working, and how you could fix it?

**Comment by OskarStark** [comment]
Travis is failing due to the xml lint, this shouldn't be fixed in this PR @greg0ire , what do you think?

**Comment by silasjoisten** [comment]
Actually we are want to display the timeline specific to a target. 
``Sonata\TimelineBundle\Admin\AdminExtension::getTarget(...) `` is always returning null, so it it is imposible to filter actions done to specific target. I want to overwrite the ``AdminExtension`` Class to fix the problem:

### Current: 
``` 
   /**
     * @param AdminInterface $admin
     * @param mixed          $object
     *
     * @return ComponentInterface
     */
    protected function getTarget(AdminInterface $admin, $object)
    {
        return $this->actionManager->findOrCreateComponent($admin->getClass(), $admin->id($object));
    }
```

### My Fix (just for my case)
```
    /**
     * @param AdminInterface $admin
     * @param mixed $object
     *
     * @return int
     */
    protected function getTarget(AdminInterface $admin, $object)
    {
        return $object->getId();
    }
```

**Comment by greg0ire** [comment]
> Sonata\TimelineBundle\Admin\AdminExtension::getTarget(...) is always returning null

Is that normal, or a bug?

**Comment by OskarStark** [comment]
> Is that normal, or a bug?

This is not really clear, as we have no tests for this class

**Comment by stivenllupa** [comment]
```
protected function getTarget(AdminInterface $admin, $object) 
{
    return $this->actionManager->findOrCreateComponent($admin->getClass(), $admin->id($object));
}
```
This method is responsible to "find" the `$object` identifier. Currently out of the 3 main types used by the extension :` 'target', 'target_text' and 'admin_code'` (ActionComponent) target is always `null`. This means it is **impossible** to filter timelines for specific **targets**. 

I am not sure if this is a failure of the TimelineBundle or maybe a target has to have a specific value. But in @silasjoisten case, he (we) want(s) to register the target identifier (this specific case object id) so that we can have more specific timelines in our dashboard.

**Comment by greg0ire** [comment]
> I am not sure if this is a failure of the TimelineBundle or maybe a target has to have a specific value to be considered an identifier.

Can you please find out with your debugger and figure it out? I had a look [the code does not look that hard to understand](https://github.com/stephpy/timeline-bundle/blob/master/Driver/ORM/ActionManager.php#L77)

**Comment by stivenllupa** [comment]
@greg0ire Ok, what is happening is this : 

1. AbstractActionManager resolves data for the User model -> finds component (User) -> timelines the User did some verb 
2. AdminExtension -> sends correct class name and id to the action manager -> resolves data for the Other model -> cannot find component -> returns null. 

I am not too deep into the bundle, so it looks like only user actions are directly timelined and the "affected" entities by the user action are not timelined (they are passively retrieved by the user action), but this causes the `type => target` to have a `text => null`.  

So, it is easy to filter actions that specific users did, and specific actions (create, delete, update) that all or specific users did. But it is not possible (without using native sql queries) to get all/specific actions all/specific users did to a specific entity. 

In @silasjoisten project the identifier is a simple id. So, it makes sense for his project that has such timeline requirements to automatically bypass the try to resolve the target identifier by directly returning the object identifier for `target`. 

Then the Extensions executes these: 

1. AbstractActionManager resolves data for the User model -> finds component (User) -> timelines the User did some verb 
2. AdminExtension -> returns the object identifier directly and the timeline action sets the `target` directly with the object id. 

Then you can build criterias like : I want all "updates" done by "superuser" to "foo" with id "34".

**Comment by greg0ire** [comment]
@stephpy, can you help with this? I don't know the bundle at all…

**Comment by stivenllupa** [comment]
@greg0ire Yes that is also true, but the whole idea of this PR is to make it easier to change the service without having to do too much configuration. If the policy for this stays, then I would see fit to add more use cases to the bundle, no?

**Comment by greg0ire** [comment]
> If the policy for this stays, then I would see fit to add more use cases to the bundle, no?

It's the goal of the closed API: have people come here to report issues they have b/c the bundle is not flexible enough and have them propose PR to fix them in the best possible way.

**Pull request closed without merging**
