### PR TITLE
added missing *.xliff extension

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
I don't understand. You didn't added a xliff file but just delete another file.

**Comment by Soullivaneuh** [comment]
I think you missing something on your commit. :-)

**Comment by OskarStark** [comment]
fixxed

**Comment by Soullivaneuh** [comment]
Thanks! :+1:

**Comment by OskarStark** [comment]
Thank you!

**Pull request merged**
