### PR TITLE
Cleanup required dependencies

### PR DESCRIPTION
**Pull request by core23**
The ``SonataCoreBundle`` and ``SonataIntlBundle`` aren't used anywhere.

### CODE REVIEW

**Comment by core23** [comment]
Can you check this @OskarStark 

Would create a new stable release after this.

**Comment by greg0ire** [comment]
> The SonataCoreBundle and SonataIntlBundle aren't used anywhere. 

This should be part of the commit message.

**Comment by greg0ire** [comment]
I checked for the intl bundle, @j0k3r required it in cc1c47e5b903405b9f9596c927730e7135d0413e
`format_date` is still present here : https://github.com/sonata-project/SonataTimelineBundle/blob/master/Resources/views/Block/timeline.html.twig

**Comment by greg0ire** [comment]
@eko  added the core bundle in bba3b6aecbcc373bda72cbb4183b5be09d67f9c5 , but didn't say why… @eko do you remember?

**Comment by j0k3r** [comment]
@greg0ire here is why: https://github.com/sonata-project/SonataTimelineBundle/pull/7

**Comment by core23** [comment]
You're quite good :+1:  Haven't looked at the twig templates...

**Comment by greg0ire** [comment]
Too bad json doesn't allow comments… or that these templates did not come with integration tests (not easy to write I guess).

**Pull request closed without merging**
