### PR TITLE
rename variable names

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
I think you made something wrong with your commits...

**Comment by OskarStark** [comment]
you are right, will have a look on that later

**Comment by OskarStark** [comment]
updated @Soullivaneuh

**Comment by Soullivaneuh** [comment]
You still have 5 commit on this PR.

Squash them with fixup method, this should fix it.

**Comment by OskarStark** [comment]
hmm there is one more commit from you, strange... why?

**Comment by Soullivaneuh** [comment]
Yes, and an old one.

What did you exactly done?

**Comment by OskarStark** [comment]
i'm not sure :)

**Comment by OskarStark** [comment]
maybe i rebased on the new master?

**Comment by OskarStark** [comment]
i removed the branch locally and made the change again, then forced the branch to update!

should be fine now @Soullivaneuh

**Comment by Soullivaneuh** [comment]
Thank you @OskarStark.

**Pull request merged**
