### PR TITLE
Missing dependencies

### PR DESCRIPTION
**Pull request by core23**
These dependencies are required for the following files:

**easy-extends**
https://github.com/sonata-project/SonataTimelineBundle/blob/master/DependencyInjection/SonataTimelineExtension.php#L103-L181

**doctrine-bridge**
https://github.com/sonata-project/SonataTimelineBundle/blob/master/Spread/AdminSpread.php#L52

**orm**
https://github.com/sonata-project/SonataTimelineBundle/blob/master/Spread/AdminSpread.php#L79-L93

### CODE REVIEW

**Comment by OskarStark** [comment]
ping @Soullivaneuh

**Comment by Soullivaneuh** [comment]
I don't know for this bundle.

ping @sonata-project/contributors

**Comment by core23** [comment]
@rande Can you have a look?

**Comment by core23** [comment]
Any news on this?

**Comment by core23** [comment]
@OskarStark Could you merge this, as there is no feedback by anyone else :(

**Comment by OskarStark** [comment]
yes, thank you @core23

**Comment by core23** [comment]
Thank you :+1:

**Pull request merged**
