### PR TITLE
Fix the subject generated link.

### LINKED ISSUE #170: Subject link goes to the target admin.
#### Sonata packages

```
sonata-project/admin-bundle              3.34.1 3.35.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1 3.12.1 Symfony SonataBlockBundle
sonata-project/cache                     1.1.1  2.0.1  Cache library
sonata-project/cache-bundle              2.4.2  2.4.2  This bundle provides caching services
sonata-project/classification-bundle     3.6.1  3.6.1  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.9.1  3.9.1  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.5.0  3.5.1  Symfony Sonata / Integrate Doctrine ORM into the SonataAdmin...
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.8.0  1.8.0  Lightweight Exporter library
sonata-project/formatter-bundle          3.4.1  3.4.1  Symfony SonataFormatterBundle
sonata-project/intl-bundle               2.4.0  2.4.0  Symfony SonataIntlBundle
sonata-project/media-bundle              3.12.0 3.12.0 Symfony SonataMediaBundle
sonata-project/news-bundle               3.4.0  3.4.0  Symfony SonataNewsBundle
sonata-project/notification-bundle       3.4.0  3.4.0  Symfony SonataNotificationBundle
sonata-project/page-bundle               3.8.0  3.8.0  This bundle provides a Site and Page management through cont...
sonata-project/seo-bundle                2.5.1  2.5.1  Symfony SonataSeoBundle
sonata-project/timeline-bundle           3.3.0  3.3.0  Integrates SpyTimelineBundle into Sonata
sonata-project/translation-bundle        2.3.0  2.3.0  SonataTranslationBundle
sonata-project/user-bundle               4.1.1  4.1.1  Symfony SonataUserBundle
```

#### Symfony packages

```
symfony/monolog-bundle     v3.2.0 v3.2.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.4.8 v4.0.8 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.7.0 v1.7.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.7.0 v1.7.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.7.0 v1.7.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.7.0 v1.7.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.7.0 v1.7.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.7.0 v1.7.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1 v3.0.1 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7 v3.2.2 Symfony SwiftmailerBundle
symfony/symfony            v3.4.8 v4.0.8 The Symfony PHP framework
```

#### PHP version

```
PHP 7.1.13 (cli) (built: Jan  9 2018 00:41:00) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.13, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

## Subject

The link for the subject redirects you to the target admin. It might come from the fact that, in the file ``timeline.html.twig``, it also uses the entry to generate the link :
```
{% set subject_text = sonata_timeline_generate_link(subject, entry) %}
```

## Steps to reproduce

- After a fresh install
- Set the timeline block like :
````
sonata_admin:
    dashboard:
        blocks:
            -
                class:    col-lg-6 col-xs-12
                position: right
                type:     sonata.timeline.block.timeline
                settings:
                    context:      GLOBAL
                    max_per_page: 25
````
- Create a user named patatesupreme for example with the role: ROLE_SUPER_ADMIN (You can also use the command `php bin/console fos:user:create patatesupreme --super-admin`)
- Connect yourself to your application using patatesupreme. The timeline should be empty.
- Create a new media with patatesupreme.
- Go back to the dashboard. The timeline should contain the media creation by patatesupreme.
- Click on patatesupreme username in the timeline which is the subject of the creation of a media.

## Expected results

You arrive on the edit page of the user patatesupreme.

## Actual results

You arrive on the edit page of the media created earlier.

### PR DESCRIPTION
**Pull request by PATATESUPREME**
I am targeting this branch, because this is BC.

Closes #170 

## Changelog

```markdown
### Fixed
- Fix the subject generated link.
```

## Subject

The link for the subject redirects you to the target admin. The modification fixes this behavior by only passing the subject without the action.

### CODE REVIEW

**Comment by PATATESUPREME** [comment]
@kunicmarko20 I've changed it.

**Comment by kunicmarko20** [comment]
cc @sonata-project/contributors can someone confirm this should be done?

**Comment by greg0ire** [comment]
Please format your commit message according to our rules : 

- The commit message subject must be less than 50 characters and tell us *what* you did.
- The commit message body should tell us *why* you did it. It is optional but highly recommended.

Bad example :

```
Fixed bug #989 by removing call to defraculate()
```

Good example:

```
Remove call to defraculate()

Calling this function caused a bug because it interferes 
with calls to getSchmeckles().
Fixes #989
```

More details in CONTRIBUTING.md

**Comment by PATATESUPREME** [comment]
@greg0ire Does the commit look better now ?

**Comment by greg0ire** [comment]
It is, but you still cannot understand why you do this without going on github. There should be a whole paragraph in the commit message about this.

**Comment by greg0ire** [comment]
I understood what happens, now tell me if I understand the why: providing a second argument (here, a user) to the generate link method will make it call getAdmin, and this gives the second argument the priority when deciding which admin to find. So if a user changes a media, it will lead to… the user admin. This looks a bit weird to me, but I think your fix is probably the best non BC-breaking fix.

**Comment by PATATESUPREME** [comment]
It's close but that's not the why.
First of all, the second argument is an `Action`(create, update or delete).
Then, this `Action` is composed of components. (target, target_text, admin_code and subject)
The type admin_code of `ActionCompenent` is the target `Admin`.

Then if you look tat the function `getAdmin()` of [`SonataTimelineExtension`](https://github.com/sonata-project/SonataTimelineBundle/blob/3.x/src/Twig/Extension/SonataTimelineExtension.php), it takes a `Component` and an `Action`. 
The first `Admin` searched is the `ActionComponent` of type admin_code which is the target `Admin` as said earlier.
And only then the `Component` `Admin` is searched.

Is the cause a bit clearer ? Or are some details a bit fuzzy ?

**Comment by PATATESUPREME** [comment]
Hello @greg0ire 

Do you have some time to look at my answer, thank you ?
If you need more details or precision, don't hesitate.

**Comment by kunicmarko20** [comment]
Same, still seems weird but if it breaks something we will know soon :smile:

**Comment by greg0ire** [comment]
Yolomerge :ship: , thanks @PATATESUPREME !

**Pull request merged**
