### PR TITLE
Removed inherited validateBlock method

### PR DESCRIPTION
**Pull request by core23**

### CODE REVIEW

**Comment by OskarStark** [comment]
ping @Soullivaneuh

**Comment by Soullivaneuh** [comment]
To be merged when on green Travis.

**Comment by OskarStark** [comment]
@core23 

can you please fix the CS:
```
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
   1) Twig/Extension/SonataTimelineExtension.php (phpdoc_params)
```

**Comment by Soullivaneuh** [comment]
@OskarStark This is not related to this PR but this one: https://github.com/sonata-project/SonataTimelineBundle/pull/59

Please fix it on the main branch.

Next time, double check PR status before merging, thanks.

**Comment by OskarStark** [comment]
:+1:  @Soullivaneuh

**Pull request merged**
